// Mocks generated by Mockito 5.3.0 from annotations
// in finance_with_notion/test/repository/transaction/notion_impl/notion_database_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:finance_with_notion/shared/httpRequest/http_request.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HttpRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpRequest extends _i1.Mock implements _i2.HttpRequest {
  MockHttpRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setBaseUrl(String? baseUrl) =>
      super.noSuchMethod(Invocation.method(#setBaseUrl, [baseUrl]),
          returnValueForMissingStub: null);
  @override
  void setHeader(Map<String, String>? hearder) =>
      super.noSuchMethod(Invocation.method(#setHeader, [hearder]),
          returnValueForMissingStub: null);
  @override
  _i3.Future<dynamic> get(String? url) =>
      (super.noSuchMethod(Invocation.method(#get, [url]),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> put(String? url, {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#put, [url], {#body: body}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> post(String? url, {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#post, [url], {#body: body}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> delete(String? url, {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#delete, [url], {#body: body}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> patch(String? url, {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#patch, [url], {#body: body}),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
}
